version: '3'
services:
  web:
    build:
      context: ./web
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./web:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-file.sql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
